server:
  port: 8019

spring:
  application:
    name: GestUserWebService
  data:
    mongodb:
      uri: mongodb://localhost:27018/ms-users
  messages:
    basename: messages_it, messages_us

jwt:
  uri: /auth
  refresh: /refresh
  tokenHeader: Authorization
  prefix: Bearer
  expiration: 86400
  secret: mySecretKey