server:
  port: 8019

spring:
  application:
    name: GestUser
  data:
    mongodb:
      uri: mongodb://localhost:27018/ms-users
  messages:
    basename: messages_it, messages_us

# ==============================================================
# = Parametri Sicurezza JWT
# ==============================================================
sicurezza:
  uri: /auth
  refresh: /refresh
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: mySecretKey

gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/username/
  username: Admin
  password: VerySecretPwd