# ==============================================================
# = Autentication Server JWT
# ==============================================================

spring:
    application:
        name: AUTH-SERVICE

server:
    port: 9101

# ==============================================================
# = Parametri Servizio gestUser
# ==============================================================
gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/username/
  userId: admin
  password: VerySecretPwd

# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: mySecretKey

# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org.springframework.security: DEBUG


        

  
 