# ==============================================================
# = Articoli Web Service con Autenticazione JWT
# ==============================================================
server:
  port: 5051
spring:
  application:
      name: ProductsWebService
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  sql:
    init:
      mode: always
      platform: postgres
  messages:
    basename: messages_it, messages_us

# ==============================================================
# = Proprietà Servizio GestUser
# ==============================================================
gestuser:
  srvUrl : http://localhost:8019/api/utenti/cerca/username/
  username : admin
  password : VerySecretPwd

# ==============================================================
# = Parametri Sicurezza JWT
# ==============================================================
sicurezza:
  uri: /auth
  refresh: /refresh
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: mySecretKey

# ==============================================================
# = Opzioni Open Feign
# ==============================================================
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
# ==============================================================
# = Configurazione livello di log PriceClient
# ==============================================================
logging:
  level:
    com:
      xantrix:
        webapp:
          controller:
            PriceClient: DEBUG