# ==============================================================
# = Promo Web Service con Autenticazione JWT
# ==============================================================

server:
  port: 8091

spring:
  application:
    name: PromoWebService
# ==============================================================
# = Proprietà Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  sql:
    init:
      mode: always
      platform: postgres
  messages:
    basename: messages_it, messages_us
    
# ==============================================================
# = Proprietà Servizio gestUser
# ==============================================================
gestuser:
  srvUrl : http://localhost:8019/api/utenti/cerca/username/
  username : admin
  password : VerySecretPwd
  
# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
  uri: /auth
  refresh: /refresh
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: mySecretKey
    
# ==============================================================
# = Configurazione levello di Log PriceClient
# ==============================================================      
logging:
  level:
    com:
      xantrix:
        webapp:
          controller:
            ArticoliClient: DEBUG
  

